excluded_list = [
    "NoticeId",
    "Sol#",
    "CGAC",
    "FPDS Code",
    "AAC Code",
    "PostedDate",
    "Office",
    "ClassificationCode",
    "Type",
    "BaseType",
    "ArchiveType",
    "ArchiveDate", 
    "SetASideCode", 
    "ResponseDeadLine", 
    "PopStreetAddress", 
    "PopCity", 
    "PopState", 
    "PopCountry",
    "PopZip",
    "Active", 
    "AwardDate", 
    "PrimaryContactFax",
    "PrimaryContactPhone",
    "PrimaryContactEmail",
    "SecondaryContactFax",
    "SecondaryContactTitle",
    "SecondaryContactFullname",
    "SecondaryContactEmail",
    "SecondaryContactPhone",
    "OrganizationType",
    "State",
    "City",
    "ZipCode",
    "CountryCode",
    "AdditionalInfoLink",
    ]